---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Oslo"
        - name: "RECIPE_PUBLIC"
          value: "true"
        - name: "RECIPE_SHOW_NUTRITION"
          value: "true"
        - name: "RECIPE_SHOW_ASSETS"
          value: "true"
        - name: "RECIPE_LANDSCAPE_VIEW"
          value: "true"
        - name: "RECIPE_DISABLE_COMMENTS"
          value: "true"
        - name: "RECIPE_DISABLE_AMOUNT"
          value: "false"
        
        volumeMounts:
        - name: {{ .Values.name }}
          mountPath: /app/data
        ports:
        - containerPort: {{ .Values.port.targetPort }}
      volumes:
      - name: {{ .Values.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.name }}-storage
