apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grocy
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: grocy
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/apps/grocy
    repoURL: '{{ .Values.repoURL }}'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
