---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.certificate.name }}-tls
  issuerRef:
    name: {{ .Values.certificate.issuer }}
    kind: ClusterIssuer
  commonName: "{{ .Values.certificate.dns }}"
  dnsNames:
  - "{{ .Values.certificate.dns }}"