---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        imagePullPolicy: Always
        volumeMounts:
        - name: {{ .Values.name }}
          mountPath: /config
        ports:
        - containerPort: {{ .Values.port.targetPort }}
      volumes:
      - name: {{ .Values.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.name }}-storage
