apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
   requests:
      storage: 2Gi