---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: {{ .Values.port.name }}
    targetPort: {{ .Values.port.targetPort }}
    port: {{ .Values.port.port }}